FROM alpine:latest
RUN apk add squashfs-tools 	p7zip

###  pentoo Varriant 
### FROM alpine:3.7 as builder

#ARG BOOTSTRAP
#FROM ${BOOTSTRAP:-alpine:latest} as builder
#RUN apk add squashfs-tools 	p7zip

#WORKDIR /gentoo
